### ISSUE TITLE
Complete installation docs and add to NPM

### ISSUE THREAD

**Issue by Bam4d** [ryanvalentin/disqus-react#1]
Would be great if this module was uploaded to NPM so users could use `npm install disqus-react`

Other disqus modules I have tried have not been working for me.

I had to install this one manually.

**Comment by ryanvalentin** [comment]
We just discussed this and it looks like we're going to put this on NPM shortly. Thanks for chiming in!

**Comment by ryanvalentin** [comment]
This is on NPM now: https://www.npmjs.com/package/disqus-react
