### ISSUE TITLE
Disqus DiscussionEmbed disappears on mobile

### ISSUE THREAD

**Issue by idiglove** [ryanvalentin/disqus-react#115]
### Describe the bug  
The embed loads but after certain time the iframe disappears, thus the comments are not displayed anymore

### To Reproduce  

I'm using it as 
```
<DiscussionEmbed shortname={disqusShortname} config={disqusConfig} />
```

### Expected behavior  
The iframe shouldnt be gone and still persist

### Screengrab
https://user-images.githubusercontent.com/29911508/136882943-d46a4f2f-1256-4691-9ab8-618de991660e.mp4

### Specifications:  
 - OS: Chrome
 - Package version: ^1.1.2
 - Node version: 14.16.1

**Comment by tterb** [comment]
@idiglove Can you provide a public repo that can be used to debug this issue and/or a link to the effected website?

**Comment by idiglove** [comment]
This has been resolved, using the native disqus comment worked
Using CommentCount component somehow affected it
